### ISSUE TITLE
Add default value to visibility

### ISSUE THREAD

**Issue by sestrella** [DeterminateSystems/flakehub-push#103]
To reduce the number of parameters required by this action, I'd propose making `unlisted` the default value for the `visibility` input, as it would allow maintainers to review the content before it gets indexed. Any thoughts?

**Comment by cole-h** [comment]
I think I'd prefer to keep `visibility` the way it is and make the user explicitly choose if they want it to be `unlisted` or not. I don't think either default (`public` or `unlisted`) makes sense for every flake, and so it's better to leave the choice up to the maintainer. IMHO, being explicit in this case is much better and much less surprising.
