### ISSUE TITLE
flakehub-push crashes when an org name isn't the same case as the registered org

### ISSUE THREAD

**Issue by COLAMAroro** [DeterminateSystems/flakehub-push#76]
I'm publishing from my personal account "COLAMAroro" (mixed case), but the flakehub generator created the PR as "colamaroro" (all lowercase, easier to type). GitHub doesn't distinguish between the two, but flakehub-publish does

See this run: https://github.com/COLAMAroro/nixos-config/actions/runs/6040458885/job/16391332523

## Error
```
Error: 
   0: Status 403 Forbidden from metadata POST
      "Releasing under another organization is not allowed\nAttempted to publish a release to the `colamaroro` organization, but release is coming from the `COLAMAroro` organization"
```

## Metadata
|key|value|
|--|--|
|**version**|0.1.0|
|**os**|linux|
|**arch**|x86_64|

## SpanTrace

<details>

```
SpanTrace:
   0: flakehub_push::cli::push_new_release
           with repository=COLAMAroro/nixos-config mirror=false upload_name=colamaroro/nixos-config source=/nix/store/15l7bc3fw6yhlwksh5shziknpagnrhvs-source
             at src/cli/mod.rs:464
   1: flakehub_push::cli::flakehub_push
             at src/cli/mod.rs:246
```
</details>

**Comment by grahamc** [comment]
Thank you for the report! In the backend, we also store the typed case but generally match on lowercase. It looks like we missed a spot :).

**Comment by grahamc** [comment]
We'll need handle the comparison carefully, and not accidentally make two non-equal strings equal due to lowercasing or other munging that might happen by mistake. I've made a ticket for it, and hopefully we'll get it early next week 👍. Thanks!
