### ISSUE TITLE
flakehub-push crashes on recursive devShell

### ISSUE THREAD

**Issue by COLAMAroro** [DeterminateSystems/flakehub-push#77]
flakehub-push expects everything in `devShells` (and I also assume `packages`) to be a derivation, but it's not required.

See this run: https://github.com/COLAMAroro/nixos-packages/actions/runs/6040518084/job/16391499518

## Error
```
Error: 
   0: Checking flake evaluates
   1: Failed to execute command `nix flake show --all-systems --json --no-write-lock-file /home/runner/work/nixos-packages/nixos-packages/` with status 1 
      stdout: 
      stderr: 
[K
[Kevaluating ''...
      evaluating 'devShells'...
      evaluating 'devShells.x86_64-linux'...
      evaluating 'devShells.x86_64-linux.python'...
      error: expected a derivation


```

## Metadata
|key|value|
|--|--|
|**version**|0.1.0|
|**os**|linux|
|**arch**|x86_64|

## SpanTrace

<details>

```
SpanTrace:
   0: flakehub_push::flake_info::check_flake_evaluates
           with directory=/home/runner/work/nixos-packages/nixos-packages/
             at src/flake_info.rs:54
   1: flakehub_push::cli::push_new_release
           with repository=COLAMAroro/nixos-packages mirror=false upload_name=COLAMAroro/nixos-packages
             at src/cli/mod.rs:464
   2: flakehub_push::cli::flakehub_push
             at src/cli/mod.rs:246
```
</details>

**Comment by grahamc** [comment]
Hi, thanks for the report. You're right that Nix does technically allow for deviating from the established norms in Nix's definition of devShells (and packages...) However, `nix flake show` errors and that's an important part of our validation steps. We think the predictability of these standard formats is really valuable, and makes Nix more easy to use.

Maybe something like flake-schemas would be interesting to you? https://determinate.systems/posts/flake-schemas This lets you define your own schema, with your own nesting rules.
