### ISSUE TITLE
Setting `name` causes release links to be broken

### ISSUE THREAD

**Issue by kip93** [DeterminateSystems/flakehub-push#83]
If you have a repo `a/b` and set this action name so that is shows up as `a/c` on flakehub, then the releases in flakehub will link commits to `https://github.com/a/c/tree/COMMIT_SHA` instead of `https://github.com/a/b/tree/COMMIT_SHA`.

Example:
* Repo: https://github.com/kip93/nixplusplus
* FlakeHub releases: https://flakehub.com/flake/kip93/npp/releases
* Screenshot:
  ![example](https://github.com/DeterminateSystems/flakehub-push/assets/26793632/2aaf6ce8-4a47-48af-82dd-bc2734cdf028)

**Comment by grahamc** [comment]
Ohp, good catch! I'm testing a fix now.

**Comment by grahamc** [comment]
I fixed all the cases of this bug that I could find, @kip93. Please re-open if you find other cases? Thank you!

**Comment by kip93** [comment]
Unfortunately I just found another instance of this issue. When there's a relative link in the flake's README, it points to an URL using the overriden name rather than the repo's name.

Both of these fail:
* `[foo](./foo)`
* `<img src="foo.svg" alt="foo">`

Now, at the very least the image used to work, so this might be a recent regression (relatively speaking, I don't check much on the flakehub page).

**Comment by kip93** [comment]
Can't seem to reopen the issue :/

**Comment by cole-h** [comment]
Thanks for letting us know. We'll look into it!

**Comment by cole-h** [comment]
@kip93 Sorry this issue reared its ugly head again, and that it took so long to get around to it, but this should be fixed going forward!

You'll need to publish a new release to fix the linking, but after that it shouldn't be wrong again. :crossed_fingers:
