### ISSUE TITLE
Nix 2.18 lock issues

### ISSUE THREAD

**Issue by kip93** [DeterminateSystems/flakehub-push#88]
After updating nix on my machine and running `nix flake update`, the lock now has a new `lastModified` attribute for tarballs that this action does not like.

Can reproduce locally. Doing `nix run nix/2.18.0 -- flake show` works, while `nix run nix/2.17.0 -- flake show` throws the same error.

## Error
```
Error: 
   0: Checking flake evaluates
   1: Failed to execute command `nix flake show --all-systems --json --no-write-lock-file /home/runner/work/nixplusplus/nixplusplus/` with status 1 
      stdout: 
      stderr: 
[K
[Kerror:
             … while updating the lock file of flake 'git+file:///home/runner/work/nixplusplus/nixplusplus?ref=refs/heads/main&rev=1545dbfa321f944874eb02262fb5214a30a292e7&shallow=1'

             error: unsupported tarball input attribute 'lastModified'


```

## Metadata
|key|value|
|--|--|
|**version**|0.1.0|
|**os**|linux|
|**arch**|x86_64|

## SpanTrace

<details>

```
SpanTrace:
   0: flakehub_push::flake_info::check_flake_evaluates
           with directory=/home/runner/work/nixplusplus/nixplusplus/
             at src/flake_info.rs:54
   1: flakehub_push::cli::push_new_release
           with repository=kip93/nixplusplus mirror=false upload_name=kip93/npp
             at src/cli/mod.rs:466
   2: flakehub_push::cli::flakehub_push
             at src/cli/mod.rs:254
```
</details>

**Comment by cole-h** [comment]
I think most common Nix versions in use have had the `lastModified` backport applied to them now (2.17.1 doesn't have the problem, nor do 2.16.2 or 2.15.3). See if you can upgrade your Nix to those patched versions!
