### ISSUE TITLE
Just when I thought my CI worked perfectly

### ISSUE THREAD

**Issue by GetPsyched** [DeterminateSystems/flakehub-push#91]
## Error
```
Error: 
   0: Checking flake evaluates
   1: Failed to execute command `nix flake show --all-systems --json --no-write-lock-file /home/runner/work/nix-starter-flakes/nix-starter-flakes/python` with status 1 
      stdout: 
      stderr: 
[K
[Kevaluating ''...
      copying path '/nix/store/i6hq63805y784dml4j8pgkrz3lryxzld-source' from 'https://cache.nixos.org'...
      evaluating 'packages'...
      evaluating 'packages.aarch64-darwin'...
      evaluating 'packages.aarch64-darwin.default'...
      evaluating 'packages.aarch64-darwin.vscode'...
      error: expected a derivation


```

## Metadata
|key|value|
|--|--|
|**version**|0.1.0|
|**os**|linux|
|**arch**|x86_64|

## SpanTrace

<details>

```
SpanTrace:
   0: flakehub_push::flake_info::check_flake_evaluates
           with directory=/home/runner/work/nix-starter-flakes/nix-starter-flakes/python
             at src/flake_info.rs:54
   1: flakehub_push::cli::push_new_release
           with repository=GetPsyched/nix-starter-flakes mirror=false upload_name=GetPsyched/python-env
             at src/cli/mod.rs:467
   2: flakehub_push::cli::flakehub_push
             at src/cli/mod.rs:254
```
</details>

**Comment by GetPsyched** [comment]
Ah, I see why the error is. My `vscode` package is a function now instead of a regular package. This lets me pass in extensions if needed. How can I resolve this?

Relevant code: https://github.com/GetPsyched/nix-starter-flakes/blob/ea89bf0d8c547df46c6bfcd7eec7b64fc7238d81/nix/flake.nix#L19-L32

**Comment by GetPsyched** [comment]
I guess there might be a way to make the derivation overridable somehow instead of wrapping it in a function. Any opinions/alternatives?

**Comment by cole-h** [comment]
You could adapt the `rofi` plugin pattern (probably not started by the `rofi` derivation, but its the one I'm most familiar with): https://github.com/NixOS/nixpkgs/blob/5bdf6eccd7509040429383523a0cc9abdaf49508/pkgs/applications/misc/rofi/wrapper.nix#L1

Specifically, look at the `plugins ? []` argument. You set that with `rofi.override { plugins = [ ... ]; }` and it pretty much does what you'd expect. Here's how I use it in my overlays: https://github.com/cole-h/nixos-config/blob/97b76000979f1aebff32d2da626277cec939d0be/lib/overlay.nix#L18

**Comment by GetPsyched** [comment]
Thanks! Took me a little while to understand how this adapts to flakes but it worked!
