### ISSUE TITLE
Cannot push due to nix flake metadata

### ISSUE THREAD

**Issue by EricTheMagician** [DeterminateSystems/flakehub-push#99]
Hi,

The action log is here:
[updating the lock file](https://github.com/EricTheMagician/ipfs-podcasting.nix/actions/runs/6983981434/job/19006024527)

## Error
```
Error: 
   0: Failed to execute command `nix flake metadata --json --no-update-lock-file /home/runner/work/ipfs-podcasting.nix/ipfs-podcasting.nix/` with status 1 
      stdout: 
      stderr: 
[K
[Kerror:
             … while updating the lock file of flake 'git+file:///home/runner/work/ipfs-podcasting.nix/ipfs-podcasting.nix?ref=refs/heads/main&rev=68c8f249db3e719087e1f424088fe238ba9ea867&shallow=1'

             error: flake 'git+file:///home/runner/work/ipfs-podcasting.nix/ipfs-podcasting.nix?shallow=1' requires lock file changes but they're not allowed due to '--no-update-lock-file'


```

## Metadata
|key|value|
|--|--|
|**version**|0.1.0|
|**os**|linux|
|**arch**|x86_64|

## SpanTrace

<details>

```
SpanTrace:
   0: flakehub_push::cli::push_new_release
           with repository=EricTheMagician/ipfs-podcasting.nix mirror=false upload_name=EricTheMagician/ipfs-podcasting.nix source=/nix/store/0kqk8605qnhl4r4wf36c165dsaqpca77-source
             at src/cli/mod.rs:472
   1: flakehub_push::cli::flakehub_push
             at src/cli/mod.rs:257
```
</details>
The strange part is that I can run  `nix flake metadata --json --no-update-lock-file ` locally without any issues.

What can I do?

**Comment by cole-h** [comment]
This error typically appears when you are trying to publish a flake with an out-of-date `flake.lock`.

If you manually run `nix flake lock`, does `git status` show that your `flake.lock`  was modified?

* If yes, commit the modified `flake.lock`, and everything should work again.
* If no, what version of Nix are you running? `nix --version`

**Comment by EricTheMagician** [comment]
For the `nix flake lock`, that was the first thing I tried.
After updating it, I got that specific error.

On my system, it's nix version `2.13.6`, so I'll get that updated and try again.

**Comment by EricTheMagician** [comment]
The lock file changed for html escaping after updating my nix. It's all good now.
